## <font color="red">練習1</font>

In [2]:
import random
from math import dist
f=open('names.csv')

last_names = []
first_names = []
name = []

out_file = '110207420_data.csv'
fout = open(out_file, 'w')

for i in range(100):
    aline = f.readline()
    line = aline.strip()
    delimeter=","
    s1,s2,s3 = line.split(delimeter)
    
    last_names.append(s3)
        
    first_names.append(s1)
    first_names.append(s2)
    
for i in range(150):
    l_name = random.choice(last_names)
    f_name = random.choice(first_names)
    full_name = '{},{}'.format(f_name, l_name)
    print('full_name: ', full_name)
    
    subject = random.randint(3,8)
    print("credits = ",subject)
    person = str(full_name)
    person += str(',')  
    
    for j in range(int(subject)):
        credits= random.randint(1,4)
        person += str(credits)
        person += str(",")
        
        grades = random.randint(1,100)
        person += str(grades)
        person += str(",")
    
    
    n_person = person[:-1]
    print(n_person)
    
    print(" ")  
    print("--------------------")
    print(" ") 
    
    persons = '{}'.format(n_person) 
    
    name.append(full_name)
    fout.write('{}\n'.format(persons))
     
def histogram(s):
    d = dict()
    for c in s:
        if c not in d:
            d[c] = 1
        else:
            d[c] += 1
            
    return d

print('name = ', name)
print(" ")  
print("----------CHECK----------")
print(" ") 
result = histogram(name)
print(result)

fout.close()
print(" ")  
print("--------------------")
print(" ") 
print('done')

full_name:  Margot,Lewis
credits =  7
Margot,Lewis,4,47,3,40,1,95,3,13,1,21,1,67,1,24

--------------------

full_name:  Luna,Ruiz
credits =  5
Luna,Ruiz,1,91,3,42,1,13,4,50,3,32

--------------------

full_name:  Zara,Chavez
credits =  8
Zara,Chavez,2,94,1,20,2,21,4,88,3,50,4,23,1,71,2,35

--------------------

full_name:  Arthur,Ramirez
credits =  4
Arthur,Ramirez,3,2,3,4,3,99,3,59

--------------------

full_name:  Joshua,Allen
credits =  3
Joshua,Allen,1,44,2,17,2,92

--------------------

full_name:  Layla,Foster
credits =  4
Layla,Foster,4,6,2,48,2,39,2,37

--------------------

full_name:  Emma,Thompson
credits =  3
Emma,Thompson,3,87,1,79,3,23

--------------------

full_name:  Daniel,Ward
credits =  5
Daniel,Ward,2,49,2,63,3,29,3,46,1,42

--------------------

full_name:  Heidi,Jimenez
credits =  3
Heidi,Jimenez,4,79,2,4,2,56

--------------------

full_name:  Poppy,Anderson
credits =  4
Poppy,Anderson,1,63,2,66,3,67,1,55

--------------------

full_name:  Evie,Thompson
credits =  3
Evie,Thompson,2,68,3,11,2,20

--------------------

full_name:  Daniel,Young
credits =  4
Daniel,Young,2,45,3,53,2,9,1,87

--------------------

full_name:  Thea,Baker
credits =  8
Thea,Baker,3,18,1,16,1,94,1,69,2,48,1,44,1,15,4,59

--------------------

full_name:  Maeve,Lopez
credits =  8
Maeve,Lopez,4,26,1,65,1,47,2,96,3,42,4,36,1,46,3,48

--------------------

full_name:  Iris,Jackson
credits =  4
Iris,Jackson,1,44,2,47,4,77,3,21

--------------------

full_name:  Ada,Gutierrez
credits =  7
Ada,Gutierrez,1,51,3,27,3,69,1,98,2,10,4,34,4,29

--------------------

full_name:  Sofia,Morales
credits =  7
Sofia,Morales,1,13,1,26,4,72,3,2,1,28,1,65,1,77

--------------------

full_name:  Thomas,Hill
credits =  3
Thomas,Hill,1,51,3,85,2,25

--------------------

full_name:  Frederick,Taylor
credits =  4
Frederick,Taylor,1,73,2,12,1,17,4,69

--------------------

full_name:  Bobby,Perez
credits =  4
Bobby,Perez,2,38,2,53,3,39,1,19

--------------------

full_name:  Samuel,Ward
credits =  6
Samuel,Ward,4,2,1,99,4,14,2,58,1,84,3,11

--------------------

full_name:  Lucy,Hughes
credits =  8
Lucy,Hughes,4,8,3,90,1,66,2,51,1,65,2,90,2,7,1,3

--------------------

full_name:  Rory,Phillips
credits =  8
Rory,Phillips,1,34,2,48,3,22,4,91,1,45,1,51,3,53,4,87

--------------------

full_name:  Samuel,Lee
credits =  6
Samuel,Lee,2,90,3,84,1,88,2,86,1,22,3,69

--------------------

full_name:  Mila,Ross
credits =  3
Mila,Ross,3,90,3,50,4,48

--------------------

full_name:  Aurora,Reed
credits =  3
Aurora,Reed,2,87,3,18,3,40

--------------------

full_name:  Olive,Ramos
credits =  3
Olive,Ramos,4,82,1,76,3,8

--------------------

full_name:  Finn,Collins
credits =  3
Finn,Collins,1,47,1,84,2,31

--------------------

full_name:  Hannah,Parker
credits =  3
Hannah,Parker,2,76,2,96,2,78

--------------------

full_name:  Emma,Miller
credits =  8
Emma,Miller,1,29,3,55,2,87,2,3,2,51,4,29,4,70,2,25

--------------------

full_name:  Rose,Mendoza
credits =  7
Rose,Mendoza,3,10,3,71,4,67,2,30,4,34,2,60,3,91

--------------------

full_name:  Bobby,Rodriguez
credits =  6
Bobby,Rodriguez,2,47,2,31,4,57,1,96,3,9,2,49

--------------------

full_name:  Mia,Foster
credits =  7
Mia,Foster,3,88,3,100,1,75,2,66,1,50,2,51,3,60

--------------------

full_name:  Milo,Allen
credits =  6
Milo,Allen,3,69,3,21,4,67,3,20,4,18,1,16

--------------------

full_name:  Ada,Williams
credits =  7
Ada,Williams,2,40,1,72,2,21,2,30,4,86,4,73,3,14

--------------------

full_name:  Eleanor,Watson
credits =  8
Eleanor,Watson,2,84,4,88,2,2,3,91,1,9,4,9,1,8,2,39

--------------------

full_name:  Sophia,King
credits =  4
Sophia,King,2,80,4,89,4,96,4,76

--------------------

full_name:  Poppy,Cook
credits =  8
Poppy,Cook,1,29,2,90,4,81,1,79,1,77,4,40,4,24,4,18

--------------------

full_name:  Maryam,Diaz
credits =  6
Maryam,Diaz,4,59,4,96,2,39,2,41,1,46,3,51

--------------------

full_name:  Sebastian,Kim
credits =  8
Sebastian,Kim,1,9,4,97,3,43,2,88,3,55,4,44,2,64,3,83

--------------------

full_name:  Luna,Nelson
credits =  8
Luna,Nelson,2,57,4,30,4,70,2,93,2,73,1,80,4,35,2,18

--------------------

full_name:  Abigail,Morgan
credits =  6
Abigail,Morgan,2,100,3,21,4,37,3,85,1,73,2,22

--------------------

full_name:  Isabella,Sanders
credits =  6
Isabella,Sanders,1,82,1,47,4,26,2,75,1,75,1,41

--------------------

full_name:  Molly,Howard
credits =  6
Molly,Howard,3,75,2,17,2,45,3,52,2,93,1,38

--------------------

full_name:  Gracie,Anderson
credits =  8
Gracie,Anderson,2,49,4,94,4,63,3,19,2,45,1,73,2,15,1,11

--------------------

full_name:  Alexander,White
credits =  8
Alexander,White,3,36,2,90,4,14,3,14,2,52,4,89,4,66,4,13

--------------------

full_name:  Liam,Gonzales
credits =  8
Liam,Gonzales,3,55,3,3,3,66,2,87,4,73,3,19,2,33,2,19

--------------------

full_name:  Arlo,Kim
credits =  3
Arlo,Kim,2,94,2,45,2,38

--------------------

full_name:  Arthur,Ramirez
credits =  8
Arthur,Ramirez,3,94,2,16,3,75,1,21,1,73,1,4,1,76,2,1

--------------------

full_name:  Albert,Morgan
credits =  6
Albert,Morgan,4,60,1,93,1,84,2,22,4,41,4,43

--------------------

full_name:  Ruby,Sanders
credits =  6
Ruby,Sanders,4,62,4,39,1,29,4,25,3,97,2,34

--------------------

full_name:  Heidi,Green
credits =  8
Heidi,Green,1,11,3,52,2,29,4,44,3,75,3,60,2,34,4,90

--------------------

full_name:  Luna,Chavez
credits =  5
Luna,Chavez,4,1,4,48,2,78,2,63,3,29

--------------------

full_name:  Jessica,Gray
credits =  6
Jessica,Gray,2,63,4,89,3,23,4,11,3,51,1,55

--------------------

full_name:  Oakley,Mitchell
credits =  8
Oakley,Mitchell,2,79,3,92,3,7,2,21,3,59,4,88,2,33,4,84

--------------------

full_name:  Rory,Morgan
credits =  8
Rory,Morgan,4,91,4,56,3,79,3,86,4,95,1,29,2,27,4,10

--------------------

full_name:  Elsie,Jackson
credits =  6
Elsie,Jackson,4,88,2,8,3,52,2,22,2,33,2,25

--------------------

full_name:  Aurora,Lopez
credits =  4
Aurora,Lopez,2,43,2,83,3,54,1,1

--------------------

full_name:  Isaac,Carter
credits =  5
Isaac,Carter,2,72,4,24,1,72,3,35,3,20

--------------------

full_name:  Reuben,Walker
credits =  5
Reuben,Walker,2,6,1,87,3,16,2,62,3,45

--------------------

full_name:  Teddy,Rivera
credits =  8
Teddy,Rivera,2,20,1,34,2,71,4,41,2,73,1,16,3,32,1,10

--------------------

full_name:  Sophie,Morris
credits =  8
Sophie,Morris,2,8,4,64,4,21,3,36,2,71,2,83,2,44,3,27

--------------------

full_name:  Theodore,Hall
credits =  5
Theodore,Hall,2,17,4,45,4,95,2,43,1,47

--------------------

full_name:  Robyn,Chavez
credits =  7
Robyn,Chavez,2,3,1,35,4,92,2,93,3,35,3,83,1,53

--------------------

full_name:  Max,Watson
credits =  4
Max,Watson,2,21,2,56,1,22,2,79

--------------------

full_name:  Rory,Young
credits =  8
Rory,Young,1,35,4,89,2,55,2,24,1,58,4,66,3,22,3,84

--------------------

full_name:  Mila,Turner
credits =  5
Mila,Turner,3,75,4,82,1,67,2,99,3,48

--------------------

full_name:  William,Bailey
credits =  5
William,Bailey,3,58,2,76,2,55,2,18,4,42

--------------------

full_name:  Rory,Cooper
credits =  8
Rory,Cooper,1,57,2,28,1,39,3,5,4,84,3,99,1,37,3,68

--------------------

full_name:  Rowan,Ross
credits =  7
Rowan,Ross,1,70,2,8,4,38,1,64,1,97,2,22,2,10

--------------------

full_name:  Louie,Mitchell
credits =  4
Louie,Mitchell,2,71,1,38,2,62,2,96

--------------------

full_name:  Penelope,Jimenez
credits =  6
Penelope,Jimenez,4,82,1,44,4,92,3,93,3,47,4,80

--------------------

full_name:  Sophia,Collins
credits =  7
Sophia,Collins,2,45,2,63,3,98,2,97,2,55,1,62,4,87

--------------------

full_name:  Lyla,Gutierrez
credits =  5
Lyla,Gutierrez,3,28,1,10,4,33,1,2,3,20

--------------------

full_name:  Lottie,Smith
credits =  4
Lottie,Smith,2,71,2,20,2,95,1,2

--------------------

full_name:  Hudson,Flores
credits =  6
Hudson,Flores,1,20,4,75,1,62,1,96,1,19,3,64

--------------------

full_name:  Maria,Murphy
credits =  3
Maria,Murphy,4,89,3,42,1,44

--------------------

full_name:  Teddy,Martin
credits =  4
Teddy,Martin,2,11,1,29,4,33,4,50

--------------------

full_name:  Olive,Hernandez
credits =  5
Olive,Hernandez,1,67,4,76,3,35,2,37,1,42

--------------------

full_name:  Lucas,Anderson
credits =  7
Lucas,Anderson,3,98,4,93,3,8,2,81,1,15,4,59,4,47

--------------------

full_name:  Penelope,Jones
credits =  3
Penelope,Jones,2,48,3,74,4,56

--------------------

full_name:  Chester,Long
credits =  4
Chester,Long,4,85,4,65,3,71,3,81

--------------------

full_name:  Teddy,Chavez
credits =  3
Teddy,Chavez,1,12,4,80,4,93

--------------------

full_name:  Logan,Lee
credits =  5
Logan,Lee,2,74,3,39,2,48,2,17,3,72

--------------------

full_name:  Esme,Ward
credits =  6
Esme,Ward,1,11,3,18,2,94,4,17,2,58,3,23

--------------------

full_name:  Charlotte,Ramirez
credits =  3
Charlotte,Ramirez,3,96,3,70,3,98

--------------------

full_name:  Bonnie,Rogers
credits =  5
Bonnie,Rogers,4,59,3,61,3,73,3,58,4,59

--------------------

full_name:  Archie,Moore
credits =  6
Archie,Moore,4,23,3,59,3,31,2,78,2,75,4,32

--------------------

full_name:  Dylan,Rodriguez
credits =  7
Dylan,Rodriguez,1,50,1,69,1,89,4,80,1,30,2,42,3,31

--------------------

full_name:  Rowan,Cooper
credits =  7
Rowan,Cooper,1,54,4,6,1,23,4,55,2,24,1,11,3,16

--------------------

full_name:  Joshua,Thompson
credits =  8
Joshua,Thompson,1,85,2,27,3,63,2,71,4,56,4,53,1,91,4,83

--------------------

full_name:  Arlo,Mendoza
credits =  3
Arlo,Mendoza,1,13,2,100,4,15

--------------------

full_name:  Scarlett,Chavez
credits =  6
Scarlett,Chavez,4,63,2,2,4,64,3,72,4,83,1,62

--------------------

full_name:  Eden,Hughes
credits =  8
Eden,Hughes,4,31,3,54,3,63,2,68,2,88,4,61,3,58,4,30

--------------------

full_name:  Evie,Johnson
credits =  8
Evie,Johnson,2,26,4,38,1,89,2,4,1,6,1,100,1,84,1,70

--------------------

full_name:  Alfred,Reed
credits =  8
Alfred,Reed,4,66,3,90,3,90,1,1,1,11,4,51,2,56,3,23

--------------------

full_name:  Arabella,Baker
credits =  7
Arabella,Baker,2,66,1,24,3,29,1,8,2,71,3,2,4,91

--------------------

full_name:  Emma,Morris
credits =  7
Emma,Morris,4,79,1,2,2,90,2,83,2,14,2,27,4,41

--------------------

full_name:  Mabel,Mitchell
credits =  4
Mabel,Mitchell,1,24,3,32,4,86,1,85

--------------------

full_name:  Gabriel,Johnson
credits =  3
Gabriel,Johnson,4,16,1,74,3,24

--------------------

full_name:  Theo,Phillips
credits =  4
Theo,Phillips,4,17,1,31,3,1,3,69

--------------------

full_name:  Louis,Murphy
credits =  6
Louis,Murphy,3,17,3,43,3,23,2,24,2,38,3,25

--------------------

full_name:  Luna,Lee
credits =  6
Luna,Lee,1,41,2,52,3,40,4,3,1,69,2,59

--------------------

full_name:  Esme,Bailey
credits =  3
Esme,Bailey,2,68,4,12,1,92

--------------------

full_name:  Imogen,Taylor
credits =  6
Imogen,Taylor,2,64,4,29,3,98,2,85,4,85,1,51

--------------------

full_name:  Theo,Scott
credits =  8
Theo,Scott,4,8,2,98,1,27,3,72,4,25,4,36,1,24,2,33

--------------------

full_name:  Emma,Young
credits =  5
Emma,Young,3,15,1,18,3,51,3,18,1,67

--------------------

full_name:  Jack,Castillo
credits =  4
Jack,Castillo,4,81,4,87,4,63,1,83

--------------------

full_name:  Elodie,Williams
credits =  7
Elodie,Williams,4,51,2,92,2,21,1,37,2,17,1,45,1,86

--------------------

full_name:  Ronnie,Watson
credits =  4
Ronnie,Watson,4,86,2,87,1,66,2,19

--------------------

full_name:  Alfred,Walker
credits =  7
Alfred,Walker,3,86,4,6,2,24,2,45,1,54,3,87,2,5

--------------------

full_name:  Tommy,Miller
credits =  3
Tommy,Miller,3,5,3,1,2,1

--------------------

full_name:  Sienna,Morris
credits =  3
Sienna,Morris,4,64,2,64,2,84

--------------------

full_name:  Felix,Green
credits =  4
Felix,Green,1,6,3,93,2,80,3,95

--------------------

full_name:  Eliza,Ross
credits =  8
Eliza,Ross,2,65,4,23,1,55,3,34,4,79,1,84,1,55,1,71

--------------------

full_name:  Ella,Clark
credits =  6
Ella,Clark,1,6,4,18,3,60,4,97,3,46,2,63

--------------------

full_name:  Grace,Ortiz
credits =  4
Grace,Ortiz,2,4,3,98,1,77,4,27

--------------------

full_name:  Grayson,Sanders
credits =  5
Grayson,Sanders,1,41,3,29,4,40,2,73,1,60

--------------------

full_name:  Ronnie,Turner
credits =  7
Ronnie,Turner,1,98,4,54,4,48,4,43,1,4,4,57,2,20

--------------------

full_name:  Mabel,Adams
credits =  8
Mabel,Adams,3,15,4,65,1,73,4,22,3,76,4,21,3,47,1,28

--------------------

full_name:  Elizabeth,Adams
credits =  7
Elizabeth,Adams,2,93,4,52,2,93,4,59,4,40,2,10,3,19

--------------------

full_name:  Ivy,Peterson
credits =  3
Ivy,Peterson,2,91,1,21,1,37

--------------------

full_name:  Nancy,Diaz
credits =  5
Nancy,Diaz,3,28,3,56,1,52,1,76,2,93

--------------------

full_name:  Adam,Scott
credits =  4
Adam,Scott,1,75,2,4,4,51,2,73

--------------------

full_name:  Mila,Edwards
credits =  8
Mila,Edwards,2,59,3,47,4,92,2,100,3,87,2,52,4,1,4,64

--------------------

full_name:  Sophie,King
credits =  6
Sophie,King,3,36,4,87,1,8,3,16,3,72,1,22

--------------------

full_name:  Maria,Kim
credits =  3
Maria,Kim,3,10,1,19,2,30

--------------------

full_name:  Arlo,Cruz
credits =  6
Arlo,Cruz,1,3,3,26,2,2,3,86,1,71,1,58

--------------------

full_name:  Lily,Torres
credits =  6
Lily,Torres,3,84,1,28,3,73,4,48,1,48,2,25

--------------------

full_name:  Logan,Chavez
credits =  4
Logan,Chavez,3,69,4,49,2,98,4,4

--------------------

full_name:  Deliah,Foster
credits =  4
Deliah,Foster,4,20,2,7,1,1,3,86

--------------------

full_name:  Esme,Stewart
credits =  5
Esme,Stewart,1,15,1,94,4,91,2,78,2,88

--------------------

full_name:  Anna,James
credits =  7
Anna,James,3,53,1,27,1,22,1,29,3,35,3,34,4,28

--------------------

full_name:  Ellis,Howard
credits =  5
Ellis,Howard,2,96,1,3,1,2,3,98,4,39

--------------------

full_name:  James,Lee
credits =  8
James,Lee,3,87,4,93,1,60,4,31,4,80,2,99,1,26,1,51

--------------------

full_name:  Ellis,Cox
credits =  5
Ellis,Cox,1,54,4,91,4,95,4,54,4,37

--------------------

full_name:  Eliza,Rodriguez
credits =  7
Eliza,Rodriguez,4,54,4,41,3,97,1,56,2,9,3,10,3,84

--------------------

full_name:  Oakley,Watson
credits =  6
Oakley,Watson,4,90,2,86,4,64,2,71,1,49,3,61

--------------------

full_name:  Ronnie,Gutierrez
credits =  6
Ronnie,Gutierrez,1,77,1,2,3,23,3,28,2,18,3,61

--------------------

full_name:  Emilia,Brown
credits =  6
Emilia,Brown,3,11,4,20,2,50,3,9,4,15,4,37

--------------------

full_name:  Ellie,Reed
credits =  5
Ellie,Reed,4,29,4,73,3,20,1,80,1,94

--------------------

full_name:  Georgia,Cox
credits =  3
Georgia,Cox,3,61,3,65,1,88

--------------------

full_name:  Elsie,Martin
credits =  5
Elsie,Martin,4,2,1,77,2,87,4,100,4,44

--------------------

full_name:  Amber,Mendoza
credits =  6
Amber,Mendoza,1,52,3,87,3,6,1,51,2,90,3,21

--------------------

full_name:  Aria,Lopez
credits =  8
Aria,Lopez,1,18,2,100,4,57,1,45,3,34,4,86,2,70,3,14

--------------------

full_name:  Penelope,James
credits =  5
Penelope,James,4,56,2,9,1,16,4,55,3,69

--------------------

full_name:  Ralph,Gutierrez
credits =  5
Ralph,Gutierrez,1,14,4,95,1,60,2,77,1,4

--------------------

full_name:  Bella,Kim
credits =  6
Bella,Kim,3,71,4,88,2,55,1,12,2,65,4,35

--------------------

full_name:  Ella,Ruiz
credits =  6
Ella,Ruiz,3,81,3,65,1,100,3,71,3,54,3,6

--------------------

full_name:  Thea,Sanchez
credits =  3
Thea,Sanchez,3,84,3,54,2,59

--------------------

name =  ['Margot,Lewis', 'Luna,Ruiz', 'Zara,Chavez', 'Arthur,Ramirez', 'Joshua,Allen', 'Layla,Foster', 'Emma,Thompson', 'Daniel,Ward', 'Heidi,Jimenez', 'Poppy,Anderson', 'Evie,Thompson', 'Daniel,Young', 'Thea,Baker', 'Maeve,Lopez', 'Iris,Jackson', 'Ada,Gutierrez', 'Sofia,Morales', 'Thomas,Hill', 'Frederick,Taylor', 'Bobby,Perez', 'Samuel,Ward', 'Lucy,Hughes', 'Rory,Phillips', 'Samuel,Lee', 'Mila,Ross', 'Aurora,Reed', 'Olive,Ramos', 'Finn,Collins', 'Hannah,Parker', 'Emma,Miller', 'Rose,Mendoza', 'Bobby,Rodriguez', 'Mia,Foster', 'Milo,Allen', 'Ada,Williams', 'Eleanor,Watson', 'Sophia,King', 'Poppy,Cook', 'Maryam,Diaz', 'Sebastian,Kim', 'Luna,Nelson', 'Abigail,Morgan', 'Isabella,Sanders', 'Molly,Howard', 'Gracie,Anderson', 'Alexander,White', 'Liam,Gonzales', 'Arlo,Kim', 'Arthur,Ramirez', 'Albert,Morgan', 'Ruby,Sanders', 'Heidi,Green', 'Luna,Chavez', 'Jessica,Gray', 'Oakley,Mitchell', 'Rory,Morgan', 'Elsie,Jackson', 'Aurora,Lopez', 'Isaac,Carter', 'Reuben,Walker', 'Teddy,Rivera', 'Sophie,Morris', 'Theodore,Hall', 'Robyn,Chavez', 'Max,Watson', 'Rory,Young', 'Mila,Turner', 'William,Bailey', 'Rory,Cooper', 'Rowan,Ross', 'Louie,Mitchell', 'Penelope,Jimenez', 'Sophia,Collins', 'Lyla,Gutierrez', 'Lottie,Smith', 'Hudson,Flores', 'Maria,Murphy', 'Teddy,Martin', 'Olive,Hernandez', 'Lucas,Anderson', 'Penelope,Jones', 'Chester,Long', 'Teddy,Chavez', 'Logan,Lee', 'Esme,Ward', 'Charlotte,Ramirez', 'Bonnie,Rogers', 'Archie,Moore', 'Dylan,Rodriguez', 'Rowan,Cooper', 'Joshua,Thompson', 'Arlo,Mendoza', 'Scarlett,Chavez', 'Eden,Hughes', 'Evie,Johnson', 'Alfred,Reed', 'Arabella,Baker', 'Emma,Morris', 'Mabel,Mitchell', 'Gabriel,Johnson', 'Theo,Phillips', 'Louis,Murphy', 'Luna,Lee', 'Esme,Bailey', 'Imogen,Taylor', 'Theo,Scott', 'Emma,Young', 'Jack,Castillo', 'Elodie,Williams', 'Ronnie,Watson', 'Alfred,Walker', 'Tommy,Miller', 'Sienna,Morris', 'Felix,Green', 'Eliza,Ross', 'Ella,Clark', 'Grace,Ortiz', 'Grayson,Sanders', 'Ronnie,Turner', 'Mabel,Adams', 'Elizabeth,Adams', 'Ivy,Peterson', 'Nancy,Diaz', 'Adam,Scott', 'Mila,Edwards', 'Sophie,King', 'Maria,Kim', 'Arlo,Cruz', 'Lily,Torres', 'Logan,Chavez', 'Deliah,Foster', 'Esme,Stewart', 'Anna,James', 'Ellis,Howard', 'James,Lee', 'Ellis,Cox', 'Eliza,Rodriguez', 'Oakley,Watson', 'Ronnie,Gutierrez', 'Emilia,Brown', 'Ellie,Reed', 'Georgia,Cox', 'Elsie,Martin', 'Amber,Mendoza', 'Aria,Lopez', 'Penelope,James', 'Ralph,Gutierrez', 'Bella,Kim', 'Ella,Ruiz', 'Thea,Sanchez']

----------CHECK----------


## <font color="red">練習2</font>

In [3]:
f=open('110207420_data.csv')

out_file = '110207420_grade.csv'
fout = open(out_file, 'w')

average_grades_list=[]
average_gp_list=[]

for i in range(150):
    aline = f.readline()
    line = aline.strip()
    delimeter=","
    a = line.split(delimeter)
    print(a)
    


    
    b=a[2::2]
    b_int = list(map(int, b))
    total_credits = sum(b_int)
    print("total_credits = ", total_credits)
    
    c=a[3::2]
    c_int = list(map(int, c))
    
    k=0
    total_grades=0
    for i in range(len(b)):
        grades = b_int[k]*c_int[k]
        k+=1
        total_grades += grades
    print("total_grades = ",total_grades)
    
    average_grades=total_grades/total_credits
    print("average_grades = ",average_grades)
    
    
    k=0
    c_gp=[]
    for i in range(len(b)):
        score = c_int[k]
        k+=1
        if 100>=score>=90:
            gp = 4.3
        elif 89>=score>=85:
            gp = 4.0
        elif 84>=score>=80:
            gp = 3.7
        elif 79>=score>=77:
            gp = 3.3
        elif 76>=score>=73:
            gp = 3.0
        elif 72>=score>=70:
            gp = 2.7
        elif 69>=score>=67:
            gp = 2.3
        elif 66>=score>=63:
            gp = 2.0
        elif 62>=score>=60:
            gp = 1.7
        elif 59>=score>=50:
            gp = 1.0
        else:
            gp = 0.0
            
        c_gp.append(gp)
    print("c_gp = ",c_gp)
    
    k=0
    total_gp=0
    for i in range(len(b)):
        gp = b_int[k]*c_gp[k]
        k+=1
        total_gp += gp
        
    print("totol_gp = ",round(total_gp,1))
    
    average_gp=(round(total_gp,1))/total_credits
    print("average_gp = ",average_gp)
    
    name = a[0:2]
    delimiter = ','
    name_str = delimiter.join(name)
    
    total = '{},{},{},{}'.format(name_str, total_credits,average_grades,average_gp)
    fout.write('{}\n'.format(total))
    
    print(" ")  
    print("--------------------")
    print(" ") 
    
    
    average_grades_list.append(average_grades)
    average_gp_list.append(average_gp)
    
    
fout.close()
print('done')

['Margot', 'Lewis', '4', '47', '3', '40', '1', '95', '3', '13', '1', '21', '1', '67', '1', '24']
total_credits =  14
total_grades =  554
average_grades =  39.57142857142857
c_gp =  [0.0, 0.0, 4.3, 0.0, 0.0, 2.3, 0.0]
totol_gp =  6.6
average_gp =  0.4714285714285714

--------------------

['Luna', 'Ruiz', '1', '91', '3', '42', '1', '13', '4', '50', '3', '32']
total_credits =  12
total_grades =  526
average_grades =  43.833333333333336
c_gp =  [4.3, 0.0, 0.0, 1.0, 0.0]
totol_gp =  8.3
average_gp =  0.6916666666666668

--------------------

['Zara', 'Chavez', '2', '94', '1', '20', '2', '21', '4', '88', '3', '50', '4', '23', '1', '71', '2', '35']
total_credits =  19
total_grades =  985
average_grades =  51.8421052631579
c_gp =  [4.3, 0.0, 0.0, 4.0, 1.0, 0.0, 2.7, 0.0]
totol_gp =  30.3
average_gp =  1.5947368421052632

--------------------

['Arthur', 'Ramirez', '3', '2', '3', '4', '3', '99', '3', '59']
total_credits =  12
total_grades =  492
average_grades =  41.0
c_gp =  [0.0, 0.0, 4.3, 1.0]
totol_gp =  15.9
average_gp =  1.325

--------------------

['Joshua', 'Allen', '1', '44', '2', '17', '2', '92']
total_credits =  5
total_grades =  262
average_grades =  52.4
c_gp =  [0.0, 0.0, 4.3]
totol_gp =  8.6
average_gp =  1.72

--------------------

['Layla', 'Foster', '4', '6', '2', '48', '2', '39', '2', '37']
total_credits =  10
total_grades =  272
average_grades =  27.2
c_gp =  [0.0, 0.0, 0.0, 0.0]
totol_gp =  0.0
average_gp =  0.0

--------------------

['Emma', 'Thompson', '3', '87', '1', '79', '3', '23']
total_credits =  7
total_grades =  409
average_grades =  58.42857142857143
c_gp =  [4.0, 3.3, 0.0]
totol_gp =  15.3
average_gp =  2.185714285714286

--------------------

['Daniel', 'Ward', '2', '49', '2', '63', '3', '29', '3', '46', '1', '42']
total_credits =  11
total_grades =  491
average_grades =  44.63636363636363
c_gp =  [0.0, 2.0, 0.0, 0.0, 0.0]
totol_gp =  4.0
average_gp =  0.36363636363636365

--------------------

['Heidi', 'Jimenez', '4', '79', '2', '4', '2', '56']
total_credits =  8
total_grades =  436
average_grades =  54.5
c_gp =  [3.3, 0.0, 1.0]
totol_gp =  15.2
average_gp =  1.9

--------------------

['Poppy', 'Anderson', '1', '63', '2', '66', '3', '67', '1', '55']
total_credits =  7
total_grades =  451
average_grades =  64.42857142857143
c_gp =  [2.0, 2.0, 2.3, 1.0]
totol_gp =  13.9
average_gp =  1.9857142857142858

--------------------

['Evie', 'Thompson', '2', '68', '3', '11', '2', '20']
total_credits =  7
total_grades =  209
average_grades =  29.857142857142858
c_gp =  [2.3, 0.0, 0.0]
totol_gp =  4.6
average_gp =  0.6571428571428571

--------------------

['Daniel', 'Young', '2', '45', '3', '53', '2', '9', '1', '87']
total_credits =  8
total_grades =  354
average_grades =  44.25
c_gp =  [0.0, 1.0, 0.0, 4.0]
totol_gp =  7.0
average_gp =  0.875

--------------------

['Thea', 'Baker', '3', '18', '1', '16', '1', '94', '1', '69', '2', '48', '1', '44', '1', '15', '4', '59']
total_credits =  14
total_grades =  624
average_grades =  44.57142857142857
c_gp =  [0.0, 0.0, 4.3, 2.3, 0.0, 0.0, 0.0, 1.0]
totol_gp =  10.6
average_gp =  0.7571428571428571

--------------------

['Maeve', 'Lopez', '4', '26', '1', '65', '1', '47', '2', '96', '3', '42', '4', '36', '1', '46', '3', '48']
total_credits =  19
total_grades =  868
average_grades =  45.68421052631579
c_gp =  [0.0, 2.0, 0.0, 4.3, 0.0, 0.0, 0.0, 0.0]
totol_gp =  10.6
average_gp =  0.5578947368421052

--------------------

['Iris', 'Jackson', '1', '44', '2', '47', '4', '77', '3', '21']
total_credits =  10
total_grades =  509
average_grades =  50.9
c_gp =  [0.0, 0.0, 3.3, 0.0]
totol_gp =  13.2
average_gp =  1.3199999999999998

--------------------

['Ada', 'Gutierrez', '1', '51', '3', '27', '3', '69', '1', '98', '2', '10', '4', '34', '4', '29']
total_credits =  18
total_grades =  709
average_grades =  39.388888888888886
c_gp =  [1.0, 0.0, 2.3, 4.3, 0.0, 0.0, 0.0]
totol_gp =  12.2
average_gp =  0.6777777777777777

--------------------

['Sofia', 'Morales', '1', '13', '1', '26', '4', '72', '3', '2', '1', '28', '1', '65', '1', '77']
total_credits =  12
total_grades =  503
average_grades =  41.916666666666664
c_gp =  [0.0, 0.0, 2.7, 0.0, 0.0, 2.0, 3.3]
totol_gp =  16.1
average_gp =  1.3416666666666668

--------------------

['Thomas', 'Hill', '1', '51', '3', '85', '2', '25']
total_credits =  6
total_grades =  356
average_grades =  59.333333333333336
c_gp =  [1.0, 4.0, 0.0]
totol_gp =  13.0
average_gp =  2.1666666666666665

--------------------

['Frederick', 'Taylor', '1', '73', '2', '12', '1', '17', '4', '69']
total_credits =  8
total_grades =  390
average_grades =  48.75
c_gp =  [3.0, 0.0, 0.0, 2.3]
totol_gp =  12.2
average_gp =  1.525

--------------------

['Bobby', 'Perez', '2', '38', '2', '53', '3', '39', '1', '19']
total_credits =  8
total_grades =  318
average_grades =  39.75
c_gp =  [0.0, 1.0, 0.0, 0.0]
totol_gp =  2.0
average_gp =  0.25

--------------------

['Samuel', 'Ward', '4', '2', '1', '99', '4', '14', '2', '58', '1', '84', '3', '11']
total_credits =  15
total_grades =  396
average_grades =  26.4
c_gp =  [0.0, 4.3, 0.0, 1.0, 3.7, 0.0]
totol_gp =  10.0
average_gp =  0.6666666666666666

--------------------

['Lucy', 'Hughes', '4', '8', '3', '90', '1', '66', '2', '51', '1', '65', '2', '90', '2', '7', '1', '3']
total_credits =  16
total_grades =  732
average_grades =  45.75
c_gp =  [0.0, 4.3, 2.0, 1.0, 2.0, 4.3, 0.0, 0.0]
totol_gp =  27.5
average_gp =  1.71875

--------------------

['Rory', 'Phillips', '1', '34', '2', '48', '3', '22', '4', '91', '1', '45', '1', '51', '3', '53', '4', '87']
total_credits =  19
total_grades =  1163
average_grades =  61.21052631578947
c_gp =  [0.0, 0.0, 0.0, 4.3, 0.0, 1.0, 1.0, 4.0]
totol_gp =  37.2
average_gp =  1.9578947368421054

--------------------

['Samuel', 'Lee', '2', '90', '3', '84', '1', '88', '2', '86', '1', '22', '3', '69']
total_credits =  12
total_grades =  921
average_grades =  76.75
c_gp =  [4.3, 3.7, 4.0, 4.0, 0.0, 2.3]
totol_gp =  38.6
average_gp =  3.216666666666667

--------------------

['Mila', 'Ross', '3', '90', '3', '50', '4', '48']
total_credits =  10
total_grades =  612
average_grades =  61.2
c_gp =  [4.3, 1.0, 0.0]
totol_gp =  15.9
average_gp =  1.59

--------------------

['Aurora', 'Reed', '2', '87', '3', '18', '3', '40']
total_credits =  8
total_grades =  348
average_grades =  43.5
c_gp =  [4.0, 0.0, 0.0]
totol_gp =  8.0
average_gp =  1.0

--------------------

['Olive', 'Ramos', '4', '82', '1', '76', '3', '8']
total_credits =  8
total_grades =  428
average_grades =  53.5
c_gp =  [3.7, 3.0, 0.0]
totol_gp =  17.8
average_gp =  2.225

--------------------

['Finn', 'Collins', '1', '47', '1', '84', '2', '31']
total_credits =  4
total_grades =  193
average_grades =  48.25
c_gp =  [0.0, 3.7, 0.0]
totol_gp =  3.7
average_gp =  0.925

--------------------

['Hannah', 'Parker', '2', '76', '2', '96', '2', '78']
total_credits =  6
total_grades =  500
average_grades =  83.33333333333333
c_gp =  [3.0, 4.3, 3.3]
totol_gp =  21.2
average_gp =  3.533333333333333

--------------------

['Emma', 'Miller', '1', '29', '3', '55', '2', '87', '2', '3', '2', '51', '4', '29', '4', '70', '2', '25']
total_credits =  20
total_grades =  922
average_grades =  46.1
c_gp =  [0.0, 1.0, 4.0, 0.0, 1.0, 0.0, 2.7, 0.0]
totol_gp =  23.8
average_gp =  1.19

--------------------

['Rose', 'Mendoza', '3', '10', '3', '71', '4', '67', '2', '30', '4', '34', '2', '60', '3', '91']
total_credits =  21
total_grades =  1100
average_grades =  52.38095238095238
c_gp =  [0.0, 2.7, 2.3, 0.0, 0.0, 1.7, 4.3]
totol_gp =  33.6
average_gp =  1.6

--------------------

['Bobby', 'Rodriguez', '2', '47', '2', '31', '4', '57', '1', '96', '3', '9', '2', '49']
total_credits =  14
total_grades =  605
average_grades =  43.214285714285715
c_gp =  [0.0, 0.0, 1.0, 4.3, 0.0, 0.0]
totol_gp =  8.3
average_gp =  0.5928571428571429

--------------------

['Mia', 'Foster', '3', '88', '3', '100', '1', '75', '2', '66', '1', '50', '2', '51', '3', '60']
total_credits =  15
total_grades =  1103
average_grades =  73.53333333333333
c_gp =  [4.0, 4.3, 3.0, 2.0, 1.0, 1.0, 1.7]
totol_gp =  40.0
average_gp =  2.6666666666666665

--------------------

['Milo', 'Allen', '3', '69', '3', '21', '4', '67', '3', '20', '4', '18', '1', '16']
total_credits =  18
total_grades =  686
average_grades =  38.111111111111114
c_gp =  [2.3, 0.0, 2.3, 0.0, 0.0, 0.0]
totol_gp =  16.1
average_gp =  0.8944444444444445

--------------------

['Ada', 'Williams', '2', '40', '1', '72', '2', '21', '2', '30', '4', '86', '4', '73', '3', '14']
total_credits =  18
total_grades =  932
average_grades =  51.77777777777778
c_gp =  [0.0, 2.7, 0.0, 0.0, 4.0, 3.0, 0.0]
totol_gp =  30.7
average_gp =  1.7055555555555555

--------------------

['Eleanor', 'Watson', '2', '84', '4', '88', '2', '2', '3', '91', '1', '9', '4', '9', '1', '8', '2', '39']
total_credits =  19
total_grades =  928
average_grades =  48.8421052631579
c_gp =  [3.7, 4.0, 0.0, 4.3, 0.0, 0.0, 0.0, 0.0]
totol_gp =  36.3
average_gp =  1.9105263157894736

--------------------

['Sophia', 'King', '2', '80', '4', '89', '4', '96', '4', '76']
total_credits =  14
total_grades =  1204
average_grades =  86.0
c_gp =  [3.7, 4.0, 4.3, 3.0]
totol_gp =  52.6
average_gp =  3.757142857142857

--------------------

['Poppy', 'Cook', '1', '29', '2', '90', '4', '81', '1', '79', '1', '77', '4', '40', '4', '24', '4', '18']
total_credits =  21
total_grades =  1017
average_grades =  48.42857142857143
c_gp =  [0.0, 4.3, 3.7, 3.3, 3.3, 0.0, 0.0, 0.0]
totol_gp =  30.0
average_gp =  1.4285714285714286

--------------------

['Maryam', 'Diaz', '4', '59', '4', '96', '2', '39', '2', '41', '1', '46', '3', '51']
total_credits =  16
total_grades =  979
average_grades =  61.1875
c_gp =  [1.0, 4.3, 0.0, 0.0, 0.0, 1.0]
totol_gp =  24.2
average_gp =  1.5125

--------------------

['Sebastian', 'Kim', '1', '9', '4', '97', '3', '43', '2', '88', '3', '55', '4', '44', '2', '64', '3', '83']
total_credits =  22
total_grades =  1420
average_grades =  64.54545454545455
c_gp =  [0.0, 4.3, 0.0, 4.0, 1.0, 0.0, 2.0, 3.7]
totol_gp =  43.3
average_gp =  1.968181818181818

--------------------

['Luna', 'Nelson', '2', '57', '4', '30', '4', '70', '2', '93', '2', '73', '1', '80', '4', '35', '2', '18']
total_credits =  21
total_grades =  1102
average_grades =  52.476190476190474
c_gp =  [1.0, 0.0, 2.7, 4.3, 3.0, 3.7, 0.0, 0.0]
totol_gp =  31.1
average_gp =  1.480952380952381

--------------------

['Abigail', 'Morgan', '2', '100', '3', '21', '4', '37', '3', '85', '1', '73', '2', '22']
total_credits =  15
total_grades =  783
average_grades =  52.2
c_gp =  [4.3, 0.0, 0.0, 4.0, 3.0, 0.0]
totol_gp =  23.6
average_gp =  1.5733333333333335

--------------------

['Isabella', 'Sanders', '1', '82', '1', '47', '4', '26', '2', '75', '1', '75', '1', '41']
total_credits =  10
total_grades =  499
average_grades =  49.9
c_gp =  [3.7, 0.0, 0.0, 3.0, 3.0, 0.0]
totol_gp =  12.7
average_gp =  1.27

--------------------

['Molly', 'Howard', '3', '75', '2', '17', '2', '45', '3', '52', '2', '93', '1', '38']
total_credits =  13
total_grades =  729
average_grades =  56.07692307692308
c_gp =  [3.0, 0.0, 0.0, 1.0, 4.3, 0.0]
totol_gp =  20.6
average_gp =  1.5846153846153848

--------------------

['Gracie', 'Anderson', '2', '49', '4', '94', '4', '63', '3', '19', '2', '45', '1', '73', '2', '15', '1', '11']
total_credits =  19
total_grades =  987
average_grades =  51.94736842105263
c_gp =  [0.0, 4.3, 2.0, 0.0, 0.0, 3.0, 0.0, 0.0]
totol_gp =  28.2
average_gp =  1.4842105263157894

--------------------

['Alexander', 'White', '3', '36', '2', '90', '4', '14', '3', '14', '2', '52', '4', '89', '4', '66', '4', '13']
total_credits =  26
total_grades =  1162
average_grades =  44.69230769230769
c_gp =  [0.0, 4.3, 0.0, 0.0, 1.0, 4.0, 2.0, 0.0]
totol_gp =  34.6
average_gp =  1.330769230769231

--------------------

['Liam', 'Gonzales', '3', '55', '3', '3', '3', '66', '2', '87', '4', '73', '3', '19', '2', '33', '2', '19']
total_credits =  22
total_grades =  999
average_grades =  45.40909090909091
c_gp =  [1.0, 0.0, 2.0, 4.0, 3.0, 0.0, 0.0, 0.0]
totol_gp =  29.0
average_gp =  1.3181818181818181

--------------------

['Arlo', 'Kim', '2', '94', '2', '45', '2', '38']
total_credits =  6
total_grades =  354
average_grades =  59.0
c_gp =  [4.3, 0.0, 0.0]
totol_gp =  8.6
average_gp =  1.4333333333333333

--------------------

['Arthur', 'Ramirez', '3', '94', '2', '16', '3', '75', '1', '21', '1', '73', '1', '4', '1', '76', '2', '1']
total_credits =  14
total_grades =  715
average_grades =  51.07142857142857
c_gp =  [4.3, 0.0, 3.0, 0.0, 3.0, 0.0, 3.0, 0.0]
totol_gp =  27.9
average_gp =  1.9928571428571427

--------------------

['Albert', 'Morgan', '4', '60', '1', '93', '1', '84', '2', '22', '4', '41', '4', '43']
total_credits =  16
total_grades =  797
average_grades =  49.8125
c_gp =  [1.7, 4.3, 3.7, 0.0, 0.0, 0.0]
totol_gp =  14.8
average_gp =  0.925

--------------------

['Ruby', 'Sanders', '4', '62', '4', '39', '1', '29', '4', '25', '3', '97', '2', '34']
total_credits =  18
total_grades =  892
average_grades =  49.55555555555556
c_gp =  [1.7, 0.0, 0.0, 0.0, 4.3, 0.0]
totol_gp =  19.7
average_gp =  1.0944444444444443

--------------------

['Heidi', 'Green', '1', '11', '3', '52', '2', '29', '4', '44', '3', '75', '3', '60', '2', '34', '4', '90']
total_credits =  22
total_grades =  1234
average_grades =  56.09090909090909
c_gp =  [0.0, 1.0, 0.0, 0.0, 3.0, 1.7, 0.0, 4.3]
totol_gp =  34.3
average_gp =  1.5590909090909089

--------------------

['Luna', 'Chavez', '4', '1', '4', '48', '2', '78', '2', '63', '3', '29']
total_credits =  15
total_grades =  565
average_grades =  37.666666666666664
c_gp =  [0.0, 0.0, 3.3, 2.0, 0.0]
totol_gp =  10.6
average_gp =  0.7066666666666667

--------------------

['Jessica', 'Gray', '2', '63', '4', '89', '3', '23', '4', '11', '3', '51', '1', '55']
total_credits =  17
total_grades =  803
average_grades =  47.23529411764706
c_gp =  [2.0, 4.0, 0.0, 0.0, 1.0, 1.0]
totol_gp =  24.0
average_gp =  1.411764705882353

--------------------

['Oakley', 'Mitchell', '2', '79', '3', '92', '3', '7', '2', '21', '3', '59', '4', '88', '2', '33', '4', '84']
total_credits =  23
total_grades =  1428
average_grades =  62.08695652173913
c_gp =  [3.3, 4.3, 0.0, 0.0, 1.0, 4.0, 0.0, 3.7]
totol_gp =  53.3
average_gp =  2.317391304347826

--------------------

['Rory', 'Morgan', '4', '91', '4', '56', '3', '79', '3', '86', '4', '95', '1', '29', '2', '27', '4', '10']
total_credits =  25
total_grades =  1586
average_grades =  63.44
c_gp =  [4.3, 1.0, 3.3, 4.0, 4.3, 0.0, 0.0, 0.0]
totol_gp =  60.3
average_gp =  2.412

--------------------

['Elsie', 'Jackson', '4', '88', '2', '8', '3', '52', '2', '22', '2', '33', '2', '25']
total_credits =  15
total_grades =  684
average_grades =  45.6
c_gp =  [4.0, 0.0, 1.0, 0.0, 0.0, 0.0]
totol_gp =  19.0
average_gp =  1.2666666666666666

--------------------

['Aurora', 'Lopez', '2', '43', '2', '83', '3', '54', '1', '1']
total_credits =  8
total_grades =  415
average_grades =  51.875
c_gp =  [0.0, 3.7, 1.0, 0.0]
totol_gp =  10.4
average_gp =  1.3

--------------------

['Isaac', 'Carter', '2', '72', '4', '24', '1', '72', '3', '35', '3', '20']
total_credits =  13
total_grades =  477
average_grades =  36.69230769230769
c_gp =  [2.7, 0.0, 2.7, 0.0, 0.0]
totol_gp =  8.1
average_gp =  0.6230769230769231

--------------------

['Reuben', 'Walker', '2', '6', '1', '87', '3', '16', '2', '62', '3', '45']
total_credits =  11
total_grades =  406
average_grades =  36.90909090909091
c_gp =  [0.0, 4.0, 0.0, 1.7, 0.0]
totol_gp =  7.4
average_gp =  0.6727272727272727

--------------------

['Teddy', 'Rivera', '2', '20', '1', '34', '2', '71', '4', '41', '2', '73', '1', '16', '3', '32', '1', '10']
total_credits =  16
total_grades =  648
average_grades =  40.5
c_gp =  [0.0, 0.0, 2.7, 0.0, 3.0, 0.0, 0.0, 0.0]
totol_gp =  11.4
average_gp =  0.7125

--------------------

['Sophie', 'Morris', '2', '8', '4', '64', '4', '21', '3', '36', '2', '71', '2', '83', '2', '44', '3', '27']
total_credits =  22
total_grades =  941
average_grades =  42.77272727272727
c_gp =  [0.0, 2.0, 0.0, 0.0, 2.7, 3.7, 0.0, 0.0]
totol_gp =  20.8
average_gp =  0.9454545454545454

--------------------

['Theodore', 'Hall', '2', '17', '4', '45', '4', '95', '2', '43', '1', '47']
total_credits =  13
total_grades =  727
average_grades =  55.92307692307692
c_gp =  [0.0, 0.0, 4.3, 0.0, 0.0]
totol_gp =  17.2
average_gp =  1.323076923076923

--------------------

['Robyn', 'Chavez', '2', '3', '1', '35', '4', '92', '2', '93', '3', '35', '3', '83', '1', '53']
total_credits =  16
total_grades =  1002
average_grades =  62.625
c_gp =  [0.0, 0.0, 4.3, 4.3, 0.0, 3.7, 1.0]
totol_gp =  37.9
average_gp =  2.36875

--------------------

['Max', 'Watson', '2', '21', '2', '56', '1', '22', '2', '79']
total_credits =  7
total_grades =  334
average_grades =  47.714285714285715
c_gp =  [0.0, 1.0, 0.0, 3.3]
totol_gp =  8.6
average_gp =  1.2285714285714284

--------------------

['Rory', 'Young', '1', '35', '4', '89', '2', '55', '2', '24', '1', '58', '4', '66', '3', '22', '3', '84']
total_credits =  20
total_grades =  1189
average_grades =  59.45
c_gp =  [0.0, 4.0, 1.0, 0.0, 1.0, 2.0, 0.0, 3.7]
totol_gp =  38.1
average_gp =  1.905

--------------------

['Mila', 'Turner', '3', '75', '4', '82', '1', '67', '2', '99', '3', '48']
total_credits =  13
total_grades =  962
average_grades =  74.0
c_gp =  [3.0, 3.7, 2.3, 4.3, 0.0]
totol_gp =  34.7
average_gp =  2.6692307692307695

--------------------

['William', 'Bailey', '3', '58', '2', '76', '2', '55', '2', '18', '4', '42']
total_credits =  13
total_grades =  640
average_grades =  49.23076923076923
c_gp =  [1.0, 3.0, 1.0, 0.0, 0.0]
totol_gp =  11.0
average_gp =  0.8461538461538461

--------------------

['Rory', 'Cooper', '1', '57', '2', '28', '1', '39', '3', '5', '4', '84', '3', '99', '1', '37', '3', '68']
total_credits =  18
total_grades =  1041
average_grades =  57.833333333333336
c_gp =  [1.0, 0.0, 0.0, 0.0, 3.7, 4.3, 0.0, 2.3]
totol_gp =  35.6
average_gp =  1.9777777777777779

--------------------

['Rowan', 'Ross', '1', '70', '2', '8', '4', '38', '1', '64', '1', '97', '2', '22', '2', '10']
total_credits =  13
total_grades =  463
average_grades =  35.61538461538461
c_gp =  [2.7, 0.0, 0.0, 2.0, 4.3, 0.0, 0.0]
totol_gp =  9.0
average_gp =  0.6923076923076923

--------------------

['Louie', 'Mitchell', '2', '71', '1', '38', '2', '62', '2', '96']
total_credits =  7
total_grades =  496
average_grades =  70.85714285714286
c_gp =  [2.7, 0.0, 1.7, 4.3]
totol_gp =  17.4
average_gp =  2.4857142857142853

--------------------

['Penelope', 'Jimenez', '4', '82', '1', '44', '4', '92', '3', '93', '3', '47', '4', '80']
total_credits =  19
total_grades =  1480
average_grades =  77.89473684210526
c_gp =  [3.7, 0.0, 4.3, 4.3, 0.0, 3.7]
totol_gp =  59.7
average_gp =  3.142105263157895

--------------------

['Sophia', 'Collins', '2', '45', '2', '63', '3', '98', '2', '97', '2', '55', '1', '62', '4', '87']
total_credits =  16
total_grades =  1224
average_grades =  76.5
c_gp =  [0.0, 2.0, 4.3, 4.3, 1.0, 1.7, 4.0]
totol_gp =  45.2
average_gp =  2.825

--------------------

['Lyla', 'Gutierrez', '3', '28', '1', '10', '4', '33', '1', '2', '3', '20']
total_credits =  12
total_grades =  288
average_grades =  24.0
c_gp =  [0.0, 0.0, 0.0, 0.0, 0.0]
totol_gp =  0.0
average_gp =  0.0

--------------------

['Lottie', 'Smith', '2', '71', '2', '20', '2', '95', '1', '2']
total_credits =  7
total_grades =  374
average_grades =  53.42857142857143
c_gp =  [2.7, 0.0, 4.3, 0.0]
totol_gp =  14.0
average_gp =  2.0

--------------------

['Hudson', 'Flores', '1', '20', '4', '75', '1', '62', '1', '96', '1', '19', '3', '64']
total_credits =  11
total_grades =  689
average_grades =  62.63636363636363
c_gp =  [0.0, 3.0, 1.7, 4.3, 0.0, 2.0]
totol_gp =  24.0
average_gp =  2.1818181818181817

--------------------

['Maria', 'Murphy', '4', '89', '3', '42', '1', '44']
total_credits =  8
total_grades =  526
average_grades =  65.75
c_gp =  [4.0, 0.0, 0.0]
totol_gp =  16.0
average_gp =  2.0
